version: '3.1'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
  node:
    restart: always
    build: 
      context: .
      dockerfile: ./dev.Node.Dockerfile
    container_name: node
    environment:
      - NODE_ENV=development
    tty: true
    volumes:
      - .:/app:consistent
  app:
    restart: always
    build:
      context: .
      dockerfile: ./dev.Dockerfile 
    container_name: flask_app
    command: flask run --host=0.0.0.0
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    volumes:
      - .:/app:consistent