version: '3.1'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
  app:
    restart: always
    build: .
    container_name: flask_app
    entrypoint: /bin/bash -c "flask run --host=0.0.0.0 --debug"
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    volumes:
      - .:/app:consistent